-- Hardening: enforce RLS for all user-scoped business tables
ALTER TABLE public.profiles FORCE ROW LEVEL SECURITY;
ALTER TABLE public.viagens FORCE ROW LEVEL SECURITY;
ALTER TABLE public.voos FORCE ROW LEVEL SECURITY;
ALTER TABLE public.hospedagens FORCE ROW LEVEL SECURITY;
ALTER TABLE public.transportes FORCE ROW LEVEL SECURITY;
ALTER TABLE public.despesas FORCE ROW LEVEL SECURITY;
ALTER TABLE public.tarefas FORCE ROW LEVEL SECURITY;
ALTER TABLE public.documentos FORCE ROW LEVEL SECURITY;
ALTER TABLE public.bagagem FORCE ROW LEVEL SECURITY;
ALTER TABLE public.restaurantes FORCE ROW LEVEL SECURITY;
ALTER TABLE public.viajantes FORCE ROW LEVEL SECURITY;
ALTER TABLE public.preparativos FORCE ROW LEVEL SECURITY;
